### ISSUE TITLE
model around the nose

### ISSUE THREAD

**Issue by gilbertohasnofb** [awall086/c152#12]
see post by D-ECHO: http://forum.flightgear.org/viewtopic.php?f=4&t=27894&sid=405ba5a5e2b75500212e819c5ca513d1&p=272416#p272416

**Comment by gilbertohasnofb** [comment]
@awall086 do you know what that does exactly? I am super busy and I can't check it in the sim right now :cry:

**Comment by awall086** [comment]
@gilbertohasnofb I will try this suggest today, but I do not know, what exactly is the problem that this solution solves..

**Comment by gilbertohasnofb** [comment]
So that makes two of us, Adrian :smile:
