### ISSUE TITLE
Right side N80271 displayed mirrored

### ISSUE THREAD

**Issue by mathieugouin** [awall086/c152#22]
It makes it un-redable.

**Comment by mathieugouin** [comment]
But, thank you very much for this aircraft!  I just tried it and was able to take off and land.  Very good job!

**Comment by mathieugouin** [comment]
![2018-12-18-203854](https://user-images.githubusercontent.com/11562302/50193933-b69de900-0306-11e9-986e-dce811e5c1bd.png)

**Comment by awall086** [comment]
Corrected in 2020.1.1A version
