### ISSUE TITLE
Multiplayer map does not show icon

### ISSUE THREAD

**Issue by mathieugouin** [awall086/c152#25]
This one, I'm not sure if it's a setting in the aircraft code or in the multiplayer map server (http://mpmap02.flightgear.org/v3/)

Compare the red aircraft icon for the c172p:
![c172_mp_icon](https://user-images.githubusercontent.com/11562302/50258989-3643ba80-03d0-11e9-92ec-366ed33a8891.png)

vs

the c152 icon (none):

![c152_mp_icon](https://user-images.githubusercontent.com/11562302/50259000-40fe4f80-03d0-11e9-868a-4c7461b2942c.png)

**Comment by mathieugouin** [comment]
But I want to point out that even without icon, I was able to see the aircraft information box moving around as I was flying, so the aircraft seems to send data to the server.

Thanks again!
Here to help :)

**Comment by magnetic-eagle** [comment]
@mathieugouin this is actually the wrong place to point this out - the aircraft developer can do more or less nothing about it. You'd need to put this issue at the repository of the mpmap code.

**Comment by mathieugouin** [comment]
@TheFGFSEagle  sorry for the late reply... could you point me to where this repository is?  Thanks!

**Comment by magnetic-eagle** [comment]
sure thing, here you go: https://github.com/pigeond/fgmap !

**Comment by mathieugouin** [comment]
I tried again and the A/C icon is now displayed.

![image](https://user-images.githubusercontent.com/11562302/210150412-63247377-04df-4fe8-b5d1-5bfea0aca59a.png)

Closing the issue now.
