### ISSUE TITLE
Some objects disappear depending on angle or distance

### ISSUE THREAD

**Issue by gilbertohasnofb** [awall086/c152#5]
Some objects disappear depending on angle or distance. Could this be related to the `<scale>` block? Example: the magneto switch can only be viewed at a certain distance after it has been scaled (before it worked well):

![mag](https://cloud.githubusercontent.com/assets/5700795/11561660/1d2758e6-99c9-11e5-97fe-d3f1302929ca.jpg)

Some of the instruments also display this problem.

@awall086 do you think you could add the user **wlbragg** to the repository? He knows much more about these sort of things than I do, and I am sure he would be willing to help.

**Comment by awall086** [comment]
![fgfs-screen-003](https://cloud.githubusercontent.com/assets/15947578/11609829/76ba4110-9b91-11e5-8952-6c663dd87b23.png)

New layout with 2 VORs and 1 ADF. Now we have a new Amp gauge in the latest right hole of the panel. #5 Primary instruments of the upper panel not disappear depending on angle or distance. I'll work in the other objects of the lower side of the panel.

**Comment by gilbertohasnofb** [comment]
@awall086 It's looking great, I really like the new layout and the new Amp gauge! It puzzles me that `<scale>` is causing this issue, I just don't understand why is it so... but anyway, I am sure that your solution will fix this.

**Comment by awall086** [comment]
All conflictive objects are remaked to prevent objects disappear. All objects in the panel are visible in all conditions. Some labels are added to base texture and the magneto switch and has been adapted to make it more similar to the real switch.

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/15947578/11669076/00889d18-9dfb-11e5-86ed-c046948efcd0.png)

**Comment by gilbertohasnofb** [comment]
It looks great, Adrian! ~~I hope you don't mind if I use your new magneto switch in the c172p as well, as it looks great.~~ I found our reference images for the c172p and I think that the old labels look good for that project.

**Comment by gilbertohasnofb** [comment]
Also, feel free to close this issue if you think this work is done.
