### ISSUE TITLE
Make the engine instruments and fuel quantity

### ISSUE THREAD

**Issue by awall086** [awall086/c152#8]
It is necessary to make holes in the panel and create the objects and textures for engine instruments and fuel quantity.

**Comment by awall086** [comment]
![fgfs-screen-001](https://cloud.githubusercontent.com/assets/15947578/11770069/0e98ef08-a1f6-11e5-8ecf-32a112a7a8d7.png)

Engine instruments are placed and fully functional.

**Comment by gilbertohasnofb** [comment]
:+1: Great work, Adrian!
